module.exports.MESSAGE = {
  EMAIL_ALREADY_TAKEN: "Email already exists",
  SOMETHING_WENT_WRONG: "Something went wrong. Please try again.",
  ADMIN_ADD_SUCCESSFULLY: "Admin has been added successfully.",
  USER_NOT_EXIST: "User not exist.",
  PASSWORD_NOT_MATCHED: "Invalid password",
  LOGIN_SUCCESS: "Welcome User!",
  Student_ADD_SUCCESSFULLY: "Student has been added successfully.",
  STUDENT_LIST_FOUND: "Student list found successfully.",
  STUDENT_LIST_NOT_FOUND: "Student list not found.",
  DEPARTMENT_EXIST: "Department already exists",
  DEPARTMENT_ADD_SUCCESSFULLY: "Department has been added successfully.",
  DEPARTMENT_LIST_FOUND: "Department list found successfully.",
  DEPARTMENT_LIST_NOT_FOUND: "Department list not found.",
  SUBJECT_ALREADY_EXIST: "Subject already exist.",
  SUBJECT_ADDED_SUCCESSFULLY: "Subject added successfully.",
};
